FROM python:3.12-slim

WORKDIR /app

MAINTAINER Grupo 10

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_SESSION_TOKEN

ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}


RUN pip install poetry

COPY . .

RUN poetry config virtualenvs.create false
RUN poetry install

EXPOSE 8080

ARG MONGO_URL
ENV MONGO_URL=${MONGO_URL}

CMD ["python", "fiap_mpeg_uploader/__main__.py"]
