apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-uploader
  labels:
    app: uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader
  template:
    metadata:
      labels:
        app: uploader
    spec:
      containers:
        - name: uploader
          image: 115666561529.dkr.ecr.us-east-1.amazonaws.com/fiap-mpeg-uploader
          imagePullPolicy: Always
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: secret-uploader
                  key: MONGO_URL
          envFrom:
            - configMapRef:
                name: cm-uploader
          ports:
            - containerPort: 8080
